ARG BUILDKIT_INLINE_CACHE=1
FROM arm32v7/ubuntu:18.04

COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN echo working && chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
